@startuml entity-relationship-diagram
left to right direction

' avoid problems with angled crows feet
skinparam linetype ortho

together {
    entity "User" as user {
        *id: string <<generated>>
        ..
        username : varchar(64)
        email : varchar(255)
        password : varchar(255)
        bio : varchar(300) <<nullable>>
        ' url to storage of profile pictures
        profile_pic : varchar(255) <<nullable>>
        deleted_default_states : string[] <<nullable>>
        last_login : datetime
        created_on : datetime
    }

    entity "DeletedDefaultStatus" as deletedStatus {
      *user_id : string <<FK>>
      *status_id : string <<FK>>
    }

    entity "Article" as article {
        *id: string <<generated>>
        ..
        title : varchar(255)
        description : varchar(510) <<nullable>>
        link : varchar(255) <<nullable>>
        author : varchar(255)
        created_on: datetime
        updated_on: datetime
        --
        user_id : string <<FK>>
        status_id : string <<FK>>
        project_id : string <<FK>> <<nullable>>
    }
}

entity "Status" as status {
  *id : string <<generated>>
  ..
  name: varchar(255)
  description: varchar(255) <<nullable>>
  color: varchar(7)
  --
  ' user id is null for all the default states
  user_id : string <<FK>> <<nullable>>
}

entity "Project" as project {
  *id : string <<generated>>
  ..
  name: varchar(255)
  description: varchar(510)
  is_closed: boolean = false
  --
  user_id : string <<FK>>
}

' || = exactly one
' |o = zero or one
' }| = one or many
' }o = zero or many

' one user can have many articles, but one article can only have one user
user ||----o{ article
user ||----o{ status
user ||----o{ project
status ||----o{ article
article }o----o| project

@enduml
